-- ============================================================
-- Notes PWA — Supabase schema
-- Run this in the Supabase SQL editor (or via `supabase db push`)
-- ============================================================

-- Extensions
create extension if not exists "uuid-ossp";

-- Safe to re-run: drops prior objects from this schema before recreating.
-- Comment this block out once the schema is stable and has real data in it.
drop table if exists digests cascade;
drop table if exists notes cascade;
drop table if exists categories cascade;
drop type if exists source_type cascade;

-- ------------------------------------------------------------
-- Source type enum
-- ------------------------------------------------------------
create type source_type as enum ('article', 'book', 'podcast', 'video', 'other');

-- ------------------------------------------------------------
-- Categories — your own set, created ad hoc from the app
-- ------------------------------------------------------------
create table categories (
  id          uuid primary key default uuid_generate_v4(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  name        text not null,
  color       text default '#4a4a4a',       -- hex, for quick visual tagging in the UI
  created_at  timestamptz not null default now(),
  unique (user_id, name)
);

-- ------------------------------------------------------------
-- Notes — append-only. No update policy is defined on purpose.
-- ------------------------------------------------------------
create table notes (
  id              uuid primary key default uuid_generate_v4(),
  user_id         uuid not null references auth.users(id) on delete cascade,
  category_id     uuid references categories(id) on delete set null,
  quote           text not null,
  link            text,
  source_type     source_type not null default 'other',
  context         text,                      -- free text: why it mattered
  source_used_at  timestamptz not null default now(),  -- "when using" — user-editable at capture
  created_at      timestamptz not null default now(),  -- server-set, immutable
  client_id       text                        -- uuid generated on-device at capture time;
                                               -- lets the offline queue de-dupe safely on resync
);

create unique index notes_client_id_unique on notes (user_id, client_id) where client_id is not null;
create index notes_user_created_idx on notes (user_id, created_at desc);
create index notes_user_category_idx on notes (user_id, category_id);

-- ------------------------------------------------------------
-- Digests — one row per week, generated by the Saturday 10am job
-- ------------------------------------------------------------
create table digests (
  id           uuid primary key default uuid_generate_v4(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  week_start   date not null,
  week_end     date not null,
  summary      text not null,               -- Gemini-generated thematic summary
  note_count   int not null default 0,
  created_at   timestamptz not null default now(),
  unique (user_id, week_start)
);

-- ============================================================
-- Row Level Security — scoped to auth.uid(), even for single-user use
-- ============================================================
alter table categories enable row level security;
alter table notes enable row level security;
alter table digests enable row level security;

-- Categories: full CRUD for the owner
create policy "categories_select_own" on categories
  for select using (auth.uid() = user_id);
create policy "categories_insert_own" on categories
  for insert with check (auth.uid() = user_id);
create policy "categories_update_own" on categories
  for update using (auth.uid() = user_id);
create policy "categories_delete_own" on categories
  for delete using (auth.uid() = user_id);

-- Notes: select + insert only. No update/delete policy = append-only at the DB level.
create policy "notes_select_own" on notes
  for select using (auth.uid() = user_id);
create policy "notes_insert_own" on notes
  for insert with check (auth.uid() = user_id);

-- Digests: written only by the service role (Edge Function), read by the owner
create policy "digests_select_own" on digests
  for select using (auth.uid() = user_id);
-- No insert/update policy for authenticated users — the Edge Function writes
-- these using the service_role key, which bypasses RLS entirely.

-- ------------------------------------------------------------
-- Realtime — enable so notes appear live across devices
-- (wrapped to be safe on re-run: skips tables already in the publication)
-- ------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'notes'
  ) then
    alter publication supabase_realtime add table notes;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'digests'
  ) then
    alter publication supabase_realtime add table digests;
  end if;
end $$;
